version: "3.3"
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql:rw
    env_file:
      - .env
  pma:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - ${PMA_PORT}:80
    env_file:
      - .env
